#
# APPLICATION CONFIG
#

# enable gz compression
server:
  compression:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: root
    password: password
    tomcat:
      # Keep the connection alive if idle for a long time (needed in production)
      test-while-idle: true
      validation-query: SELECT 1
  profiles:
    active: dev
